---
title: "Guide to Spark Machine Learning for credit scoring"
author: "Álvaro Orgaz Expósito"
date: "29 June 2018"
output: html_document
---

# 2. DATA LOADING

Notes:

- **N5.** You can read and write data in CSV, JSON, and Parquet formats. Data can be stored in remote clusters or on the local cluster, and it returns a reference to a Spark data frame.

Load the data specifying the type of variables: numerical ("double") or categorical ("character")
```{r}
data <- spark_read_csv(sc=sc_sparklyr,
                       name="data",
                       path="Data Financed Defaults.csv",
                       header=TRUE,
                       delimiter=";",
                       infer_schema=FALSE,
                       columns=list(Contract_ID="character",
                                    Defaulted="character",
                                    Application_Hour_Group="character",
                                    Application_Week_Day="character",
                                    Amount="double",
                                    Maturity="double",
                                    Purpose="character",
                                    Province="character",
                                    Postal_Code_ASNEF="double",
                                    Age="double",
                                    Gender="character",
                                    Profession_Code="character",
                                    Profession_Sector="character",
                                    Contract_Type="character",
                                    Seniority="double",
                                    Housing_Type="character",
                                    Housing_Seniority="double",
                                    Marital_Status="character",
                                    People_in_Household="character",
                                    Income="double",
                                    Additional_Income="double",
                                    Partner_Income="double",
                                    Rent="double",
                                    Mortgage="double",
                                    Amount_of_Ongoing_Credits="double",
                                    Num_Ongoing_Credits="character"))
```

Number of customers and variables
```{r}
count(data)  ### 3468 customers
ncol(data)   ### 26 variables (including the identifier of customers)
```